version: '3'
networks:
  tgl:
    external: true

services:
  app:
    container_name: 'express-tgl-kafka'
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    image: kafka-tgl
    volumes:
      - .:/usr/ms_emails
      - /usr/ms_emails/node_modules # anonymous volume for node_modules only
    networks:
      - tgl
    ports:
      - '3339:3339'
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
       - tgl
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - tgl
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1